### ISSUE TITLE
Darwin: window.SetMargined(true) only takes affect after resize (redraw) 

### ISSUE THREAD

**Issue by nikharris0** [andlabs/ui#77]
When setting a window to be margined via SetMargined, the margin does not appear until after the window is resized. Before and after resize screenshots attached.

code:

```
package main

import (
	"github.com/andlabs/ui"
)

var window ui.Window

func main() {
	go ui.Do(func() {
		// TODO: widgets
		description := ui.NewLabel("This is a window test")

		mainStack := ui.NewVerticalStack(description)
		mainStack.SetPadded(false)

		window = ui.NewWindow("Window Test", 500, 400, mainStack)
		window.SetMargined(true)

		window.OnClosing(func() bool {
			ui.Stop()
			return true
		})

		window.Show()
	})

	err := ui.Go()
	if err != nil {
		panic(err)
	}
}
```

![after-redraw](https://cloud.githubusercontent.com/assets/794090/6203501/29666ee6-b4da-11e4-8e90-627af37051c6.png)
![before-redraw](https://cloud.githubusercontent.com/assets/794090/6203500/2961fb04-b4da-11e4-8892-3a16468bd784.png)

**Comment by andlabs** [comment]
IIRC that's a known issue and I don't know why. There might be a TODO in the code somewhere about it. I haven't touched the Darwin code in a while. Keep this issue open until it's been fixed.

**Comment by andlabs** [comment]
Fixed in libui.

OS X backend now uses Auto Layout now too to do this~

**Comment by max107** [comment]
+1. How to fix this? i update ui package and bug still exists.

**Comment by andlabs** [comment]
Package ui is not updated yet. That will happen once libui gains Area and Table again.
